language: c
compiler: gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y fakeroot
  - sudo apt-get install -y build-essential
  - sudo apt-get install -y autoconf
  - sudo apt-get install -y automake
  - sudo apt-get install -y flex
  - sudo apt-get install -y texlive
  - sudo apt-get install -y texinfo
  - sudo apt-get install -y texi2html
  - sudo apt-get install -y e2fslibs-dev
script: ./configure --prefix=/usr && make all
