.TH DISKD 1 "5mar1995" "fdutils" "fdutils"
.de BP
.sp
.ti \-.2i
\(**
..
.SH NAME
diskd \- disk daemon; wait for disk to be inserted
.SH SYNOPSIS
.hy 0
.na
.B diskd
[\fB\-d \fIdrive\fR]
[\fB\-i \fIinterval\fR]
[\fB\-e \fIcommand\fR]
.ad b
.hy 1
.SH DESCRIPTION
Diskd waits for a disk to be inserted into a given
.I drive\c
, and then either executes the
.I command 
or exits. This program can be used to automatically mount a disk as
soon as it is inserted.
.SH WARNING
This program works by switching the motor on for a very short
interval, and then seeking to track -1. This might damage hardware in
the long run. Amiga disk drives are known to have difficulties to
start up after a while. (Amigas also use this technique to
automatically mount disks as soon as they are inserted.
.SH OPTIONS
.TP
.BI "-d " "drive"
Selects the drive to observe for disk insertion. By default, drive 0
.RI ( /dev/fd0 )
is observed.
.TP
.BI "-i " "interval"
Selects the polling interval. The interval is given in tenths of
seconds. Default is 10 (one second).
.TP
.BI "-e " "command"
Gives the command to be executed when a disk is inserted. If no
command is given the program simply exits. Typically, the command
mounts the disk. It can be a shell scripts which probes for several
filesystems and disk geometries until it succeeds.
.SH BUGS
Automatic unmounting cannot yet be handled. It is indeed not enough
to scan for disk removal, because that would be too late: There might
be some buffers needing flushing.
.PP
The drive motor is running all the time, and on some computers, the
drive led flickers at each time the drive is polled.
.SH FILES
/dev/fd* - Floppy devices
.SH AUTHOR
Alain Knaff, Alain.Knaff@inrialpes.fr
.SH SEE ALSO
.BR superformat (1),
.BR getfdprm (1),
.BR floppycontrol (1),
.BR fdrawcmd (1)
