.TH MAKEFLOPPIES 1 "8jan1995" "fdutils4" "fdutils4"
.de BP
.sp
.ti \-.2i
\(**
..
.SH NAME
MAKEFLOPPIES \- Creates the default floppy device nodes.
.SH SYNOPSIS
.hy 0
.na
.B MAKEFLOPPIES
.RB "[\|" \-t "\|]"
.RB "[\|" \-l "\|]"
.RB "[\|" \-v "\|]"
.RB "[\|" \-n "\|]"
.RB "[\|" drives "\|]"
.ad b
.hy 1
.SH DESCRIPTION

The MAKEFLOPPIES shell script creates the new floppy block device
files.  It uses the floppycontrol program to translate the minor
device numbers into meaningful names. It also uses these names to
decide whether to create a given block device file or not, depending on
the type of the physical drive (for instance, for a 3 1/2 drive, the
formats corresponding to a 5 1/4 drive are not created).

If you have more than two floppy drives, you need to tell the kernel
the CMOS types of those additional drives using the
.B floppy=\c
.I drive\c
,\c
.I type\c
.B ,CMOS 
lilo option.

If the
.B drives 
parameter is given, only the device nodes for the listed drives are
made. By default, all eight drives are tried.

MAKEFLOPPIES does not work if you redefine your default formats.

.B CAUTION:
MAKEFLOPPIES removes already existing floppy device nodes.

.SH OPTIONS

.TP
.B \-t
Name devices for drive type, not floppy type (e.g. fd0H720)

.TP
.B \-l
Local. Creates device nodes in the local directory, not /dev

.TP
.B \-v
Verbose

.TP
.B \-n
Dry run. (just report what would be done, do not do anything)

.SH BUGS
The Makefloppies script does not work on redefined default formats,
because it is impossible to give new names to these formats. In
that case, you need to create the additional devices manually.

.SH FILES
/dev/fd* - Floppy devices

.SH AUTHOR
Alain Knaff, Alain.Knaff@inrialpes.fr

.SH SEE ALSO
superformat(1), rawcmd(1), floppycontrol(1), mtools(1), setfdprm(8)
